spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/pharmacy_db
        username: postgres
        password: TuanDung@127

app:
    branch-name: Nha Thuoc So 1
    hotline: 1900xxxx
    
pharmacy:
  vat-rate: 8